title:              blog.nuita.net
email:              nuita.net@gmail.com
description:        賢者のためのSNS。Nuita.netの開発者ブログです。
author:             nuita.net
baseurl:            "/"
url:                "https://blog.nuita.net/"

# Social Profiles
twitter_username:   nuita_net
github_username:    kypkyp
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
